# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-06-11 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('integration_type', models.CharField(max_length=64)),
                ('integration_data', models.TextField()),
                ('module_type', models.CharField(max_length=64)),
                ('stockone_reference', models.CharField(max_length=64)),
                ('integration_reference', models.CharField(default=None, max_length=64)),
                ('status', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
