# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-06-11 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockone_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationmaster',
            name='integration_reference',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
