from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from rest_api.views import *
from rest_api.views.tally import *
#urlpatterns = patterns('rest_api.views',
tally_api = TallyAPI()

# urlpatterns = patterns('rest_api.views',
urlpatterns = [
    # Login and logout
    url(r'^wms_login/$', wms_login),
    url(r'^status/$', status),
    url(r'^logout/$', logout),
    url(r'^get_trial_user_data/$', get_trial_user_data),
    url(r'^location_master/$', location_master),
    url(r'^results_data/$', results_data),
    url(r'^home/$', home),
    url(r'^get_update_setup_state/$', get_update_setup_state),
    url(r'^load_demo_data/$', load_demo_data),
    url(r'^clear_demo_data/$', clear_demo_data),
    url(r'^save_webpush_id/', save_webpush_id),
    url(r'^service_worker_check/', service_worker_check),

    # Dashboard
    url(r'^dashboard/$', dashboard),
    url(r'^daily_stock_report/$', daily_stock_report),

    # Master
    url(r'^get_sku_data/$', get_sku_data),
    url(r'^update_sku/$', update_sku),
    url(r'^get_supplier_master_data/$', get_supplier_master_data),
    url(r'^get_supplier_update/$', get_supplier_update),
    url(r'^get_bom_data/$', get_bom_data),
    url(r'^update_supplier_values/$', update_supplier_values),
    url(r'^insert_supplier/$', insert_supplier),
    url(r'^update_sku_supplier_values/$', update_sku_supplier_values),
    url(r'^update_sku_warehouse_values/$', update_sku_warehouse_values),
    url(r'^insert_mapping/$', insert_mapping),
    url(r'^insert_wh_mapping/$', insert_wh_mapping),
    url(r'^update_customer_values/$', update_customer_values),
    url(r'^insert_customer/$', insert_customer),
    url(r'^update_corporate_values/$', update_corporate_values),
    url(r'^insert_corporate/$', insert_corporate),
    url(r'^insert_customer_sku/$', insert_customer_sku),
    url(r'^update_customer_sku_mapping/$', update_customer_sku_mapping),
    url(r'^insert_bom_data/$', insert_bom_data),
    url(r'^insert_discount/$', insert_discount),
    url(r'^add_warehouse_user/$', add_warehouse_user),
    url(r'^update_warehouse_user/$', update_warehouse_user),
    url(r'^get_warehouse_user_data/$', get_warehouse_user_data),
    url(r'^create_user/$', create_user),
    url(r'^get_supplier_list/$', get_supplier_list),
    url(r'^get_warehouse_list/$', get_warehouse_list),
    url(r'^search_customer_sku_mapping/$', search_customer_sku_mapping),
    url(r'^delete_bom_data/$', delete_bom_data),
    url(r'^delete_market_mapping/$', delete_market_mapping),
    url(r'^quality_check_data/$', quality_check_data),
    url(r'^check_wms_qc/$', check_wms_qc),
    url(r'^confirm_quality_check/$', confirm_quality_check),
    url(r'^get_vendor_data/$', get_vendor_data),
    url(r'^update_vendor_values/$', update_vendor_values),
    url(r'^insert_vendor/$', insert_vendor),
    url(r'^add_zone/$', add_zone),
    url(r'^add_location/$', add_location),
    url(r'^update_location/$', update_location),
    url(r'^get_zones_list/$', get_zones_list),
    url(r'^insert_sku/$', insert_sku),
    url(r'^upload_images/$', upload_images),
    url(r'^get_barcodes_myntra/$', get_barcodes_myntra),
    url(r'^change_warehouse_password/$', change_warehouse_password),
    url(r'^insert_sku_pack/$',insert_sku_pack),
    url(r'^get_zone_details/$',get_zone_details),
    url(r'^delete_cluster_sku/$',delete_cluster_sku),




    # url(r'^get_sku_field_names/$',get_sku_field_names),
    url(r'^create_update_custom_sku_template/$', create_update_custom_sku_template),
    # url(r'^update_custom_sku_template/$',update_custom_sku_template),
    url(r'^delete_product_attribute/$', delete_product_attribute),
    url(r'^add_size/$', add_size),
    url(r'^update_size/$', update_size),
    url(r'^add_pricing/$', add_pricing),
    url(r'^update_pricing/$', update_pricing),
    url(r'add_network/$', add_network),
    url(r'update_network/$', update_network),
    url(r'^get_seller_master_id/$', get_seller_master_id),
    url(r'^insert_seller/$', insert_seller),
    url(r'^get_sellers_list/$', get_sellers_list),
    url(r'^update_seller_values/$', update_seller_values),
    url(r'^insert_seller_margin/$', insert_seller_margin),
    url(r'^update_seller_margin/$', update_seller_margin),
    url(r'^search_template_names/$', search_template_names),
    url(r'^get_tax_data/$', get_tax_data),
    url(r'^get_pricetype_data/$', get_pricetype_data),
    url(r'^get_network_data/$', get_network_data),
    url(r'^add_or_update_tax/$', add_or_update_tax),
    url(r'^get_zone_data/$', get_zone_data),
    url(r'^search_seller_data/$', search_seller_data),
    url(r'^search_network_user/$', search_network_user),
    url(r'^get_terms_and_conditions/$', get_terms_and_conditions),
    url(r'^insert_update_terms/$', insert_update_terms),
    url(r'^delete_terms/$', delete_terms),
    url(r'^insert_staff/$', insert_staff),
    url(r'^update_staff_values/$', update_staff_values),
    url(r'^get_user_attributes_list/$', get_user_attributes_list),
    url(r'^save_update_attribute/$', save_update_attribute),
    url(r'^delete_user_attribute/$', delete_user_attribute),
    url(r'^get_distributors/$', get_distributors),
    url(r'^get_resellers/$', get_resellers),
    url(r'^get_corporates/$', get_corporates),
    url(r'^corporate_mapping_data/$', corporate_mapping_data),
    url(r'^search_corporate_data/$', search_corporate_data),
    url(r'^push_message_notification/$', push_message_notification),
    url(r'^get_zones/$', get_zones),
    url(r'^add_sub_zone_mapping/$', add_sub_zone_mapping),

    # Inbound
    url(r'^generated_po_data/$', generated_po_data),
    url(r'^validate_wms/$', validate_wms),
    url(r'^modify_po_update/$', modify_po_update),
    url(r'^confirm_po/$', confirm_po),
    url(r'^confirm_po1/$', confirm_po1),
    url(r'^delete_po_group/$', delete_po_group),
    url(r'^confirm_add_po/$', confirm_add_po),
    url(r'^raise_po_toggle/$', raise_po_toggle),
    url(r'^get_mapping_values/$', get_mapping_values),
    url(r'^add_po/$', add_po),
    url(r'^insert_inventory_adjust/$', insert_inventory_adjust),
    url(r'^delete_po/$', delete_po),
    url(r'^search_supplier/$', search_supplier),
    url(r'^search_vendor/$', search_vendor),
    url(r'^search_wms_codes/$', search_wms_codes),
    url(r'^search_corporate_names/$', search_corporate_names),
    url(r'^search_reseller_names/$', search_reseller_names),
    url(r'^search_distributor_codes/$', search_distributor_codes),
    url(r'^get_supplier_data/$', get_supplier_data),
    url(r'^update_putaway/$', update_putaway),
    url(r'^close_po/$', close_po),
    url(r'^check_returns/$', check_returns),
    url(r'^check_sku/$', check_sku),
    url(r'^create_orders_check_ean/$', create_orders_check_ean),
    url(r'^confirm_sales_return/$', confirm_sales_return),
    url(r'^get_received_orders/$', get_received_orders),
    url(r'^putaway_data/$', putaway_data),
    url(r'^raise_st_toggle/$', raise_st_toggle),
    url(r'^save_st/$', save_st),
    url(r'^update_raised_st/$', update_raised_st),
    url(r'^confirm_st/$', confirm_st),
    url(r'^get_po_data/$', get_po_data),
    url(r'^get_so_data/$', get_so_data),
    url(r'^get_suppliers_data/$', get_suppliers_data),
    url(r'^order_status/$', order_status),
    url(r'^check_serial_exists/$', check_serial_exists),
    url(r'^returns_putaway_data/$', returns_putaway_data),
    url(r'^check_imei_exists/$', check_imei_exists),
    url(r'^confirm_grn/$', confirm_grn),
    url(r'^transfer_order/$', transfer_order),
    url(r'^batch_transfer_order/$', batch_transfer_order),
    url(r'^generate_picklist/$', generate_picklist),
    url(r'^st_generate_picklist/$', st_generate_picklist),
    url(r'^confirm_vendor_received/$', confirm_vendor_received),
    url(r'^track_orders/$', track_orders),
    url(r'^cancelled_putaway_data/$', cancelled_putaway_data),
    url(r'^get_location_capacity/$', get_location_capacity),
    url(r'^generate_seller_invoice/$', generate_seller_invoice),
    url('^check_imei_qc/$', check_imei_qc),
    url('^check_return_imei/$', check_return_imei),
    url('^confirm_receive_qc/$', confirm_receive_qc),
    url('^generate_po_labels/$', generate_po_labels),
    url('^check_generated_label/$', check_generated_label),
    url('^get_receive_po_style_view/$', get_receive_po_style_view),
    url('^save_supplier_po/$', save_supplier_po),
    url('^get_po_segregation_data/$', get_po_segregation_data),
    url('^confirm_primary_segregation/$', confirm_primary_segregation),
    url('^last_transaction_details/$', last_transaction_details),
    url(r'^supplier_invoice_data/$', supplier_invoice_data),
    url(r'^move_to_po_challan/$', move_to_poc),
    url(r'^move_to_invoice/$', move_to_invoice),
    url(r'^generate_supplier_invoice/$', generate_supplier_invoice),
    url(r'^update_poc/$', update_poc),
    url(r'^update_po_invoice/$', update_po_invoice),
    url(r'^po_get_invoice_payment_tracker/$', po_get_invoice_payment_tracker),
    url(r'^po_update_payment_status/$', po_update_payment_status),
    url(r'^get_po_putaway_summary/$', get_po_putaway_summary),
    url(r'^create_rtv/$', create_rtv),
    url(r'^save_rtv/$', save_rtv),
    url(r'^get_saved_rtv_data/$', get_saved_rtv_data),
    url(r'^map_ean_sku_code/$', map_ean_sku_code),
    url(r'^get_grn_level_data/$', get_grn_level_data),
    url(r'^update_existing_grn/$', update_existing_grn),
    url(r'^confirm_central_po/$', confirm_central_po),
    url(r'^check_sku_pack_scan/$', check_sku_pack_scan),


    # Production
    url(r'^generated_jo_data/$', generated_jo_data),
    url(r'^save_jo/$', save_jo),
    url(r'^delete_jo/$', delete_jo),
    url(r'^confirm_jo/$', confirm_jo),
    url(r'^close_jo/$', close_jo),
    url(r'^get_material_codes/$', get_material_codes),
    url('^jo_generate_picklist/$', jo_generate_picklist),
    url(r'^view_rm_picklist/$', view_rm_picklist),
    url(r'^rm_picklist_confirmation/$', rm_picklist_confirmation),
    url(r'^view_confirmed_jo/$', view_confirmed_jo),
    url(r'^confirmed_jo_data/$', confirmed_jo_data),
    url(r'^save_receive_jo/$', save_receive_jo),
    url(r'^confirm_jo_grn/$', confirm_jo_grn),
    url(r'^received_jo_data/$', received_jo_data),
    url(r'^jo_putaway_data/$', jo_putaway_data),
    url(r'^check_imei/$', check_imei),
    url(r'^delete_st/$', delete_st),
    url(r'^confirm_transfer/$', confirm_transfer),
    url(r'^delete_jo_group/$', delete_jo_group),
    url(r'^confirm_jo_group/$', confirm_jo_group),
    url(r'^print_rm_picklist/$', print_rm_picklist),
    url(r'^generate_rm_po_data/$', generate_rm_po_data),
    url(r'^confirm_back_order/$', confirm_back_order),
    url(r'^generate_rm_rwo_data/$', generate_rm_rwo_data),
    url(r'^save_rwo/$', save_rwo),
    url(r'^confirm_rwo/$', confirm_rwo),
    url(r'^saved_rwo_data/$', saved_rwo_data),
    url(r'^generate_vendor_picklist/$', generate_vendor_picklist),
    url(r'^get_vendor_types/$', get_vendor_types),
    url(r'^update_rm_picklist/$', update_rm_picklist),
    url(r'^generate_jo_labels/$', generate_jo_labels),
    url(r'^check_custom_generated_label/$', check_custom_generated_label),
    url(r'^check_return_imei_scan/$', check_return_imei_scan),
    url(r'^rwo_data/$', rwo_data),
    url(r'^check__replace_imei_exists/$', check__replace_imei_exists),
    url(r'^save_replaced_serials/$', save_replaced_serials),
    url(r'^save_replaced_locations/$', save_replaced_locations),
    url(r'^get_vendor_list/$', get_vendor_list),
    url(r'^create_vendor_stock_transfer/$', create_vendor_stock_transfer),



    # Stock Locator
    url(r'^insert_move_inventory/$', insert_move_inventory),
    url(r'^confirm_cycle_count/$', confirm_cycle_count),
    url(r'^submit_cycle_count/$', submit_cycle_count),
    url(r'^get_id_cycle/$', get_id_cycle),
    url(r'^stock_summary_data/$', stock_summary_data),
    url(r'^confirm_move_inventory/$', confirm_move_inventory),
    url(r'^confirm_inventory_adjustment/$', confirm_inventory_adjustment),
    url(r'^delete_inventory/$', delete_inventory),
    url(r'^seller_stock_summary_data/$', seller_stock_summary_data),
    url(r'^get_imei_details/$', get_imei_details),
    url(r'^change_imei_status/$', change_imei_status),
    url(r'^confirm_sku_substitution/$', confirm_sku_substitution),
    url(r'^confirm_move_location_inventory/$', confirm_move_location_inventory),
    url(r'^get_sku_batches/$', get_sku_batches),
    url(r'^inventory_adj_reasons/$', inventory_adj_reasons),
    url(r'^auto_sellable_confirm/$', auto_sellable_confirm),
    url(r'^update_sellable_suggestions/$', update_sellable_suggestions),
    url(r'^get_style_level_stock/$', get_style_level_stock),
    url(r'^get_combo_sku_codes/$', get_combo_sku_codes),
    url(r'^confirm_combo_allocation/$', confirm_combo_allocation),

    # OutBound
    url(r'^batch_generate_picklist/$', batch_generate_picklist),
    url(r'^picklist_confirmation/$', picklist_confirmation),
    url(r'^view_picklist/$', view_picklist),
    url(r'^view_picked_orders/$', view_picked_orders),
    url(r'^get_customer_sku/$', get_customer_sku),
    url(r'^get_awb_shipment_details/$', get_awb_shipment_details),
    url(r'^get_awb_view_shipment_info/$', get_awb_view_shipment_info),
    url(r'^get_awb_marketplaces/$', get_awb_marketplaces),
    url(r'^get_courier_name_for_marketplaces/$', get_courier_name_for_marketplaces),
    url(r'^print_picklist_excel/$', print_picklist_excel),
    url(r'^print_picklist/$', print_picklist),
    url(r'^print_pdf_shipment_info/$',print_pdf_shipment_info),
    url('^marketplace_segregation/$', marketplace_segregation),
    url('^get_customer_data/$', get_customer_data),
    url('^insert_order_data/$', insert_order_data),
    url('^get_warehouses_list/$', get_warehouses_list),
    url('^create_stock_transfer/$', create_stock_transfer),
    url('^stock_transfer_delete/$', stock_transfer_delete),
    url('^get_marketplaces_list/$', get_marketplaces_list),
    url('^generate_po_data/$', generate_po_data),
    url('^generate_jo_data/$', generate_jo_data),
    url('^create_stock_transfer_data/$', create_stock_transfer_data),
    url('^shipment_info/$', shipment_info),
    url('^insert_shipment_info/$', insert_shipment_info),
    url('^shipment_info_data/$', shipment_info_data),
    url('^update_shipment_status/$', update_shipment_status),
    url('^get_under_taking_form/$', get_under_taking_form),
    url('^upload_signed_under_taking_form/$', upload_signed_under_taking_form),
    url('^get_signed_oneassist_form/$', get_signed_oneassist_form),
    url('^print_shipment/$', print_shipment),
    url('^get_sku_categories/$', get_sku_categories),
    url('^get_sku_catalogs/$', get_sku_catalogs),
    url('^get_sku_variants/$', get_sku_variants),
    url('^generate_order_invoice/$', generate_order_invoice),
    url('^get_product_properties/$', get_product_properties),
    url(r'^create_custom_sku/$', create_custom_sku),
    url(r'^generate_order_jo_data/$', generate_order_jo_data),
    url(r'^search_customer_data/$', search_customer_data),
    url(r'^generate_order_po_data/$', generate_order_po_data),
    url(r'^get_view_order_details/$', get_view_order_details),
    url(r'^get_stock_location_quantity/$', get_stock_location_quantity),
    url(r'^payment_tracker/$', payment_tracker),
    url(r'^get_customer_payment_tracker/$', get_customer_payment_tracker),
    url(r'^get_invoice_payment_tracker/$', get_invoice_payment_tracker),
    url(r'^get_customer_master_id/$', get_customer_master_id),
    url(r'^get_corporate_master_id/$', get_corporate_master_id),
    url(r'^search_wms_data/$', search_wms_data),
    url(r'^search_style_data/$', search_style_data),
    url(r'^update_payment_status/$', update_payment_status),
    url(r'^update_inv_payment_status/$', update_inv_payment_status),
    url(r'^get_customer_list/$', get_customer_list),
    url(r'^create_orders_data/$', create_orders_data),
    url(r'^order_category_generate_picklist/$', order_category_generate_picklist),
    url(r'^get_customer_orders/$', get_customer_orders),
    url(r'^get_customer_order_detail/$', get_customer_order_detail),
    url(r'^get_intermediate_order_detail/$', get_intermediate_order_detail),
    url(r'^generate_pdf_file/$', generate_pdf_file),
    url(r'^get_customer_cart_data/$', get_customer_cart_data),
    url(r'^insert_customer_cart_data/$', insert_customer_cart_data),
    url(r'^update_customer_cart_data/$', update_customer_cart_data),
    url(r'^delete_customer_cart_data/$', delete_customer_cart_data),
    url(r'^generate_customer_invoice/$', generate_customer_invoice),
    url(r'^generate_customer_invoice_tab/$', generate_customer_invoice_tab),
    url(r'^generate_stock_transfer_invoice/$', generate_stock_transfer_invoice),
    url(r'^seller_generate_picklist/$', seller_generate_picklist),
    url(r'^customer_invoice_data/$', customer_invoice_data),
    url('^get_custom_template_styles/$', get_custom_template_styles),
    url('^get_seller_order_details/$', get_seller_order_details),
    url(r'^get_stock_transfer_details/$', get_stock_transfer_details),
    url(r'^get_order_labels/$', get_order_labels),
    url(r'get_sub_category_styles/$', get_sub_category_styles),
    url(r'^create_custom_skus/$', create_custom_skus),
    url(r'^update_invoice/$', update_invoice),
    url(r'^get_levels/$', get_levels),
    url(r'^get_leadtimes/$', get_leadtimes),
    url(r'^insert_enquiry_data/$', insert_enquiry_data),
    url(r'^get_enquiry_data/$', get_enquiry_data),
    url(r'^get_customer_enquiry_detail/$', get_customer_enquiry_detail),
    url(r'^move_enquiry_to_order/$', move_enquiry_to_order),
    url(r'^extend_enquiry_date/$', extend_enquiry_date),
    url(r'^order_cancel/$', order_cancel),
    url(r'^intermediate_order_cancel/$', intermediate_order_cancel),
    url(r'^add_order_charges/$', add_order_charges),
    url(r'^place_manual_order/$', place_manual_order),
    url(r'^get_manual_enquiry_data/$', get_manual_enquiry_data),
    url(r'^get_manual_enquiry_detail/$', get_manual_enquiry_detail),
    url(r'^save_manual_enquiry_data/$', save_manual_enquiry_data),
    url(r'^remove_manual_enquiry_image/$', remove_manual_enquiry_image),
    url(r'^save_manual_enquiry_image/$', save_manual_enquiry_image),
    url(r'^request_manual_enquiry_approval/$', request_manual_enquiry_approval),
    url(r'^confirm_or_hold_custom_order/$', confirm_or_hold_custom_order),
    url(r'^convert_customorder_to_actualorder/$', convert_customorder_to_actualorder),
    url(r'^convert_customorder_to_enquiryorder/$', convert_customorder_to_enquiryorder),
    url(r'^notify_designer/$', notify_designer),
    url(r'^get_invoice_details/$', get_invoice_details),
    url(r'^update_cust_profile/$', update_cust_profile),
    url(r'^print_cartons_data/$', print_cartons_data),
    url(r'^print_cartons_data_view/$', print_cartons_data_view),
    url(r'^update_orders_for_approval/$', update_orders_for_approval),
    url(r'^update_cartdata_for_approval/$', update_cartdata_for_approval),
    url(r'^after_admin_approval/$', after_admin_approval),
    url(r'^order_approval_sku_details/$', order_approval_sku_details),
    url(r'^move_to_dc/$', move_to_dc),
    url(r'^move_to_inv/$', move_to_inv),
    url(r'^update_dc/$', update_dc),
    url(r'^remove_sku/$', remove_sku),
    url(r'^get_central_order_detail/$', get_central_order_detail),
    url(r'^create_order_from_intermediate_order/$', create_order_from_intermediate_order),
    url(r'^get_stock_transfer_order_details/$', get_stock_transfer_order_details),
    url(r'^update_stock_transfer_data/$', update_stock_transfer_data),
    url(r'^stock_transfer_generate_picklist/$', stock_transfer_generate_picklist),
    url(r'^invoice_mark_delivered/$', invoice_mark_delivered),
    url(r'^get_create_order_mapping_values/$', get_create_order_mapping_values),
    url(r'^get_ratings_details/$', get_ratings_details),
    url(r'^get_ratings_data_popup/$', get_ratings_data_popup),
    url(r'^save_cutomer_ratings/$', save_cutomer_ratings),
    url(r'^list_notifications/$', list_notifications), #PUSH NOTIFICATIONS
    url(r'^make_notifications_read/$', make_notifications_read),
    url(r'^delete_notification/$', delete_notification),
    url(r'^get_grn_edit_filter/$', get_grn_edit_filter),
    url(r'^get_stock_transfer_shipment_popup_data/$', get_stock_transfer_shipment_popup_data),
    url(r'^insert_st_shipment_info/$', insert_st_shipment_info),
    url(r'^do_delegate_orders/$', do_delegate_orders),
    url(r'^app_shipment_info_data/$', app_shipment_info_data),
    url(r'^confirm_order_request/$', confirm_order_request),
    url(r'^send_order_back/$', send_order_back),
    url(r'^invoice_print_manifest/$', invoice_print_manifest),
    url(r'^shipment_pack_ref/$', shipment_pack_ref),
    url(r'^shipment_pack_ref_decrease/$', shipment_pack_ref_decrease),
    url(r'^generate_picklist_dc/$', generate_picklist_dc),
    url(r'^get_order_extra_fields/$', get_order_extra_fields),
    url(r'^create_feedback_form/$', create_feedback_form),


    # Uploaded POs [SWISS MILITARY]
    url(r'^upload_po/$', upload_po),
    url(r'^get_updated_pos/$', get_updated_pos),
    url(r'^validate_po/$', validate_po),
    url(r'^pending_pos/$', pending_pos),
    url(r'^sm_cancel_order_from_uploaded_pos/$', sm_cancel_order_from_uploaded_pos),

    # Targets [SWISS MILITARY]
    url(r'^get_distributor_targets/$', get_distributor_targets),
    # Reports
    # url(r'^location_wise_filter/$',location_wise_filter),
    url(r'^get_report_data/$', get_report_data),
    url(r'^get_supplier_details/$', get_supplier_details),
    url(r'^get_sku_filter/$', get_sku_filter),
    url(r'^get_po_filter/$', get_po_filter),
    url(r'^get_sku_wise_po_filter/$', get_sku_wise_po_filter),
    url(r'^get_location_filter/$', get_location_filter),
    url(r'^get_receipt_filter/$', get_receipt_filter),
    url(r'^get_dispatch_filter/$', get_dispatch_filter),
    url(r'^get_order_summary_filter/$', get_order_summary_filter),
    url(r'^get_sku_stock_filter/$', get_sku_stock_filter),
    url(r'^get_sales_return_filter/$', get_sales_return_filter),
    url(r'^get_sku_purchase_filter/$', get_sku_purchase_filter),
    url(r'^get_inventory_adjust_filter/$', get_inventory_adjust_filter),
    url(r'^get_inventory_aging_filter/$', get_inventory_aging_filter),
    url(r'^sku_category_list/$', sku_category_list),
    url(r'^print_po_reports/$', print_po_reports),
    url(r'^print_sku/$', print_sku),
    url(r'^excel_reports/$', excel_reports),
    url(r'^print_stock_location/$', print_stock_location),
    url(r'^print_receipt_summary/$', print_receipt_summary),
    url(r'^print_dispatch_summary/$', print_dispatch_summary),
    url(r'^print_sku_wise_stock/$', print_sku_wise_stock),
    url(r'^print_sku_wise_purchase/$', print_sku_wise_purchase),
    url(r'^print_supplier_pos/$', print_supplier_pos),
    url(r'^print_sales_returns/$', print_sales_returns),
    url(r'^get_inventory_adjust_filter/$', get_inventory_adjust_filter),
    url(r'^print_adjust_report/$', print_adjust_report),
    url(r'^print_aging_report/$', print_aging_report),
    url(r'^get_stock_summary_report/$', get_stock_summary_report),
    url(r'^print_stock_summary_report/$', print_stock_summary_report),
    url(r'^get_daily_production_report/$', get_daily_production_report),
    url(r'^print_daily_production_report/$', print_daily_production_report),
    url(r'^print_order_summary_report/$', print_order_summary_report),
    url(r'^print_stock_reconciliation_report/$', print_stock_reconciliation_report),
    url(r'^print_margin_report/$', print_margin_report),
    url(r'^get_marketplaces_list_reports/$', get_marketplaces_list_reports),
    url(r'^get_seller_invoices_filter/$', get_seller_invoices_filter),
    url(r'^print_seller_invoice_report/$', print_seller_invoice_report),
    url(r'^get_rm_picklist_report/$', get_rm_picklist_report),
    url(r'^print_rm_picklist_report/$', print_rm_picklist_report),
    url(r'^excel_sales_return_report/$', excel_sales_return_report),
    url(r'^get_stock_ledger_report/$', get_stock_ledger_report),
    url(r'^print_stock_ledger_report/$', print_stock_ledger_report),
    url(r'^print_purchase_order_form/$', print_purchase_order_form),
    url(r'^get_shipment_report/$', get_shipment_report),
    url(r'^get_po_report/$', get_po_report),
    url(r'^get_open_order_report/$', get_open_order_report),
    url(r'^print_shipment_report/$', print_shipment_report),
    url(r'^print_po_report/$', print_po_report),
    url(r'^print_open_order_report/$', print_open_order_report),
    url(r'^get_dist_sales_report/$', get_dist_sales_report),
    url(r'^print_dist_sales_report/$', print_dist_sales_report),
    url(r'^get_reseller_sales_report/$', get_reseller_sales_report),
    url(r'^print_reseller_sales_report/$', print_reseller_sales_report),
    url(r'^get_zone_target_summary_report/$', get_zone_target_summary_report),
    url(r'^print_zone_target_summary_report/$', print_zone_target_summary_report),
    url(r'^get_zone_target_detailed_report/$', get_zone_target_detailed_report),
    url(r'^print_zone_target_detailed_report/$', print_zone_target_detailed_report),
    url(r'^get_dist_target_summary_report/$', get_dist_target_summary_report),
    url(r'^print_dist_target_summary_report/$', print_dist_target_summary_report),
    url(r'^get_dist_target_detailed_report/$', get_dist_target_detailed_report),
    url(r'^print_dist_target_detailed_report/$', print_dist_target_detailed_report),
    url(r'^get_reseller_target_summary_report/$', get_reseller_target_summary_report),
    url(r'^print_reseller_target_summary_report/$', print_reseller_target_summary_report),
    url(r'^get_reseller_target_detailed_report/$', get_reseller_target_detailed_report),
    url(r'^print_reseller_target_detailed_report/$', print_reseller_target_detailed_report),
    url(r'^get_corporate_target_report/$', get_corporate_target_report),
    url(r'^print_corporate_target_report/$', print_corporate_target_report),
    url(r'^get_corporate_reseller_mapping_report/$', get_corporate_reseller_mapping_report),
    url(r'^print_corporate_reseller_mapping_report/$', print_corporate_reseller_mapping_report),
    url(r'^get_enquiry_status_report/$', get_enquiry_status_report),
    url(r'^print_enquiry_status_report/$', print_enquiry_status_report),
    url(r'^get_rtv_report/$', get_rtv_report),
    url(r'^print_rtv_report/$', print_rtv_report),
    url(r'^print_debit_note/$', print_debit_note),
    url(r'^get_sku_categories_list/$', get_sku_categories_list),
    url(r'^get_sku_wise_rtv_filter/$', get_sku_wise_rtv_filter),
    url(r'^download_grn_invoice_mapping/$', download_grn_invoice_mapping),
    url(r'^get_stock_transfer_report/$', get_stock_transfer_report),
    url(r'^get_stock_reconciliation_report/$', get_stock_reconciliation_report),
    url(r'^get_margin_report/$', get_margin_report),
    url(r'^get_current_stock_report/$', get_current_stock_report),
    url(r'^print_current_stock_report/$', print_current_stock_report),
    url(r'^get_inventory_value_report/$', get_inventory_value_report),
    url(r'^print_inventory_value_report/$', print_inventory_value_report),
    url(r'^get_bulk_to_retail_report/$', get_bulk_to_retail_report),
    url(r'^print_bulk_to_retail_report/$', print_bulk_to_retail_report),
    url(r'^get_stock_cover_report/$', get_stock_cover_report),
    url(r'^print_stock_cover_report/$', print_stock_cover_report),
]

# urlpatterns += patterns('rest_api.views',

urlpatterns += [

    # uploads
    url(r'^order_form/$', order_form),
    url(r'^order_upload/$', order_upload),
    url(r'^sku_form/$', sku_form),
    url(r'^sku_upload/$', sku_upload),
    url(r'^inventory_form/$', inventory_form),
    url(r'^inventory_upload/$', inventory_upload),
    url(r'^supplier_form/$', supplier_form),
    url(r'^supplier_upload/$', supplier_upload),
    url(r'^supplier_sku_form/$', supplier_sku_form),
    url(r'^supplier_sku_upload/$', supplier_sku_upload),
    url(r'^location_form/$', location_form),
    url(r'^location_upload/$', location_upload),
    url(r'^purchase_order_form/$', purchase_order_form),
    url(r'^purchase_order_upload/$', purchase_order_upload),
    url(r'^move_inventory_form/$', move_inventory_form),
    url(r'^move_inventory_upload/$', move_inventory_upload),
    url(r'^marketplace_sku_form/$', marketplace_sku_form),
    url(r'^marketplace_sku_upload/$', marketplace_sku_upload),
    url(r'^bom_form/$', bom_form),
    url(r'^bom_upload/$', bom_upload),
    url(r'^combo_sku_form/$', combo_sku_form),
    url(r'^combo_sku_upload/$', combo_sku_upload),
    url(r'^inventory_adjust_form/$', inventory_adjust_form),
    url(r'^inventory_adjust_upload/$', inventory_adjust_upload),
    url(r'^inventory_adj_modify_qty/$', inventory_adj_modify_qty),
    url(r'vendor_form/$', vendor_form),
    url(r'vendor_upload/$', vendor_upload),
    url(r'customer_form/$', customer_form),
    url(r'customer_upload/$', customer_upload),
    url(r'^pricing_master_form/$', pricing_master_form),
    url(r'^pricing_master_upload/$', pricing_master_upload),
    url(r'^order_label_mapping_form/$', order_label_mapping_form),
    url(r'^order_label_mapping_upload/$', order_label_mapping_upload),
    url(r'^order_serial_mapping_form/$', order_serial_mapping_form),
    url(r'^order_serial_mapping_upload/$', order_serial_mapping_upload),
    url(r'^po_serial_mapping_form/$', po_serial_mapping_form),
    url(r'^po_serial_mapping_upload/$', po_serial_mapping_upload),
    url(r'^job_order_form/$', job_order_form),
    url(r'^orderid_awb_mapping_form/$', orderid_awb_mapping_form),
    url(r'^orderid_awb_upload/', orderid_awb_upload),
    url(r'^job_order_upload/$', job_order_upload),
    url(r'^marketplace_serial_form/$', marketplace_serial_form),
    url(r'^marketplace_serial_upload/$', marketplace_serial_upload),
    url(r'^seller_transfer_form/$', seller_transfer_form),
    url(r'^seller_transfer_upload/$', seller_transfer_upload),
    url(r'^network_master_form/$', network_master_form),
    url(r'^network_master_upload/$', network_master_upload),
    url(r'^sku_substitution_form/$', sku_substitution_form),
    url(r'^sku_substitution_upload/$', sku_substitution_upload),
    url(r'^targets_form/$', targets_form),
    url(r'^targets_upload/$', targets_upload),
    url(r'^central_order_form/$', central_order_form),
    url(r'^central_order_upload/$', central_order_upload),
    url(r'^stock_transfer_order_form/$',stock_transfer_order_form),
    url(r'^stock_transfer_order_upload/$',stock_transfer_order_upload),
    url(r'^skupack_master_download/$', skupack_master_download),
    url(r'^skupack_master_upload/$', skupack_master_upload),
    url(r'^block_stock_download/$', block_stock_download),
    url(r'^block_stock_upload/$', block_stock_upload),
    url(r'^custom_order_download/$', custom_order_download),
    url(r'^custom_order_upload/$', custom_order_upload),
    url(r'^cluster_sku_form/$', cluster_sku_form),
    url(r'^cluster_sku_upload/$', cluster_sku_upload),


    # configurations
    url(r'^configurations/$', configurations),
    url(r'^switches/$', switches),
    url(r'^enable_mail_reports/$', enable_mail_reports),
    url(r'^save_groups/$', save_groups),
    url(r'^update_mail_configuration/$', update_mail_configuration),
    url(r'^send_mail_reports/$', send_mail_reports),
    url(r'^save_stages/$', save_stages),
    url(r'^order_management_toggle/$', order_management_toggle),
    url(r'^order_management_check/$', order_management_check),
    url(r'^save_tally_data/$', save_tally_data),
    url(r'^delete_tally_data/$', delete_tally_data),
    url(r'^delete_tax/$', delete_tax),
    url(r'^update_invoice_sequence/$', update_invoice_sequence),
    url(r'^update_mail_alerts/$', update_mail_alerts),
    url(r'^pos_extra_fields/$',pos_extra_fields),

    # manage users
    url(r'^add_user/$', add_user),
    url(r'^add_group_data/$', add_group_data),
    url(r'^add_group/$', add_group),
    url(r'^get_user_data/$', get_user_data),
    url(r'^update_user/$', update_user),
    url(r'^get_group_data/$', get_group_data),

    # common
    url(r'^set_timezone/$', set_timezone),
    url(r'^get_file_checksum/$', get_file_checksum),
    url(r'^get_file_content/$', get_file_content),
    url(r'get_tally_data/', get_tally_data),
    url(r'get_categories_list/', get_categories_list),
    url(r'get_sku_stock_check/', get_sku_stock_check),
    url(r'check_labels/', check_labels),
    url(r'get_imei_data/', get_imei_data),
    url(r'get_user_profile_data/$', get_user_profile_data),
    url(r'get_user_profile_shipment_addresses/$', get_user_profile_shipment_addresses),
    url(r'change_user_password/$', change_user_password),
    url(r'update_profile_data/$', update_profile_data),
    url(r'update_profile_shipment_address/$', update_profile_shipment_address),
    url(r'get_cust_profile_info/$', get_cust_profile_info),
    url(r'get_linked_warehouse_names/$', get_linked_warehouse_names),
    url(r'delete_temp_json/$', delete_temp_json),
    url(r'^search_batches/$', search_batches),
    url(r'^save_order_extra_fields/$', save_order_extra_fields),
    url(r'^get_current_weight/$', get_current_weight),


    # Retailone
    url(r'^get_marketplace_data/$', get_marketplace_data),
    url(r'^update_market_status/$', update_market_status),
    url(r'^add_market_credentials/$', add_market_credentials),
    url(r'^get_marketplace_logo/$', get_marketplace_logo),
    url(r'^pull_market_data/$', pull_market_data),
    url(r'^add_market_credentials/$', add_market_credentials),

    # Integrations
    url(r'^pull_orders_now/$', pull_orders_now),
    url(r'^update_sync_issues/$', update_sync_issues),
    url(r'^order_push/$', order_push),

    # stockone
    url(r'^book_trial/$', book_trial),
    url(r'^contact_us/$', contact_us),

    # POS
    url('^validate_sales_person', validate_sales_person),
    url('^add_customer/$', add_customer),
    url('^search_pos_customer_data/$', search_pos_customer_data),
    url('^search_product_data/$', search_product_data),
    url('^get_current_order_id/$', get_current_order_id),
    url('^get_pos_user_data/$', get_pos_user_data),
    url('^customer_order/$', customer_order),
    url('^print_order_data/$', print_order_data),
    url('^pre_order_data/$', pre_order_data),
    url('^update_order_status/$', update_order_status),
    url('^get_extra_fields/$', get_extra_fields),
    url('^get_staff_members_list/$', get_staff_members_list),
    url(r'^pos_tax_inclusive/$', pos_tax_inclusive),
    url(r'^stock_transfer_invoice_data/$', stock_transfer_invoice_data),
    url(r'^pos_send_mail/$', pos_send_mail),



]

# urlpatterns += patterns('rest_api.views',
urlpatterns += [
    url(r'^update_order_data/$', update_order_data),
    url(r'^picklist_delete/$', picklist_delete),
    url(r'^delete_order_data/$', delete_order_data),
    url(r'^order_delete/$', order_delete),

    # uploads
    url(r'sales_returns_upload/$', sales_returns_upload),
    url(r'sales_returns_form/$', sales_returns_form),

    # stocklocator
    url(r'warehouse_headers', warehouse_headers),

    # reports
    url(r'get_internal_mails', get_internal_mails),
    # url(r'^get_openjo_report/$',get_openjo_report),
    url(r'^get_openjo_report_details/$', get_openjo_report_details),
    url(r'^print_open_jo_report/$', print_open_jo_report),

    # order_sync_issues
    url(r'delete_order_sync_data', delete_order_sync_data),
    url(r'order_sync_data_detail', order_sync_data_detail),
    url(r'confirm_order_sync_data', confirm_order_sync_data),

    # masters
    url(r'generate_barcodes', generate_barcodes),

    # price_master data
    url(r'get_customer_sku_prices', get_customer_sku_prices),
    url(r'get_supplier_sku_prices', get_supplier_sku_prices),

    # save_invoice_changes -> outbound
    url(r'edit_invoice', edit_invoice),
    url(r'delete_order_charges', delete_order_charges),

    # get size_list
    url(r'get_size_names', get_size_names),

    # get list of vendors . @common.py
    url(r'get_vendors_list/', get_vendors_list),

    # update_picklist_loc
    url(r'update_picklist_loc/', update_picklist_loc),

    #Tally API
    #url('^GetItemMaster/', tally_api.get_item_master),
    #url('^GetSupplierMaster/', tally_api.get_supplier_master),
    #url('^GetCustomerMaster/', tally_api.get_customer_master),

    # Barcodes
    url(r'^get_format_types/', get_format_types),
    url(r'^GetItemMaster/', tally_api.get_item_master),
    url(r'^GetSupplierMaster/', tally_api.get_supplier_master),
    url(r'^GetCustomerMaster/', tally_api.get_customer_master),
    url(r'^GetSalesInvoices/', tally_api.get_sales_invoices),
    url(r'^GetSalesReturns/', tally_api.get_sales_returns),
    url(r'^GetPurchaseInvoices/', tally_api.get_purchase_invoice),
    url(r'^GetPurchaseReturns/', tally_api.get_purchase_returns),

]
