# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVendorMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('port', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('data', models.TextField(blank=True, default='', null=True)),
                ('push_status', models.IntegerField(blank=True, db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'CUSTOMERVENDORMASTER',
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('item_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('port', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('data', models.TextField(blank=True, default='', null=True)),
                ('push_status', models.IntegerField(blank=True, db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ITEMMASTER',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('invoice_num', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('port', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('data', models.TextField(blank=True, default='', null=True)),
                ('push_status', models.IntegerField(blank=True, db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'SALESINVOICE',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('salesinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PullFromStockone.SalesInvoice')),
            ],
            options={
                'db_table': 'PURCHASEINVOICE',
            },
            bases=('PullFromStockone.salesinvoice',),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('salesinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PullFromStockone.SalesInvoice')),
            ],
            options={
                'db_table': 'PurchaseReturn',
            },
            bases=('PullFromStockone.salesinvoice',),
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('salesinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PullFromStockone.SalesInvoice')),
            ],
            options={
                'db_table': 'SalesReturn',
            },
            bases=('PullFromStockone.salesinvoice',),
        ),
    ]
