# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PullFromStockone', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customervendormaster',
            unique_together=set([('client_name', 'customer_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='itemmaster',
            unique_together=set([('client_name', 'item_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together=set([('client_name', 'invoice_num', 'order_id')]),
        ),
    ]
