var CHECK_SUM="checksum";
var SKU_MASTER="sku_master";
var SYNC_SKUMASTER="sync_sku_master";
var SYNC_CUSTOMERMASTER="sync_customer_master";
var CUSTOMER_MASTER="customer_master";
var REQUEST_METHOD_GET="get"; 
var REQUEST_METHOD_POST="post"; 
var ONLINE="online";
var OFFLINE="offline";
var GET_CURRENT_ORDER="get_order";
var ORDER_ID="order_id";
var ORDER_ID_UPDATED_ERROR="Order is not updated in local";
var SYNC_LOCAL_DATA="sync_local_data"
var USER_DATA="user_data";
var SYNC_POS_DATA="sync_pos";
var NETWORK_ERROR="activated offline mode";
var CONNECTED_NETWORK="online mode";
var NOTIIFICATION_ERROR="applicaiton need an notfication permission."
